# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(480, 500)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_5 = QtGui.QFrame(self.centralWidget)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_8 = QtGui.QLabel(self.frame_5)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_11 = QtGui.QLabel(self.frame_5)
        self.label_11.setMaximumSize(QtCore.QSize(50, 20))
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.frame_5)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_2.addWidget(self.label_12)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_4 = QtGui.QFrame(self.centralWidget)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.formLayout = QtGui.QFormLayout(self.frame_4)
        self.formLayout.setMargin(11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_9 = QtGui.QLabel(self.frame_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.lineEdit = QtGui.QLineEdit(self.frame_4)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_10 = QtGui.QLabel(self.frame_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_2 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.pushButton = QtGui.QPushButton(self.frame_4)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.pushButton)
        self.verticalLayout.addWidget(self.frame_4)
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setMaximumSize(QtCore.QSize(600, 160))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.desired_line = QtGui.QLineEdit(self.frame_2)
        self.desired_line.setObjectName(_fromUtf8("desired_line"))
        self.gridLayout_2.addWidget(self.desired_line, 1, 1, 1, 1)
        self.startbutton = QtGui.QPushButton(self.frame_2)
        self.startbutton.setObjectName(_fromUtf8("startbutton"))
        self.gridLayout_2.addWidget(self.startbutton, 4, 1, 1, 1)
        self.clear_button = QtGui.QPushButton(self.frame_2)
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.gridLayout_2.addWidget(self.clear_button, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.current_line = QtGui.QLineEdit(self.frame_2)
        self.current_line.setEnabled(False)
        self.current_line.setObjectName(_fromUtf8("current_line"))
        self.gridLayout_2.addWidget(self.current_line, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame_2)
        self.temperature_dial = QtGui.QDial(self.frame)
        self.temperature_dial.setMinimumSize(QtCore.QSize(50, 50))
        self.temperature_dial.setMaximum(150)
        self.temperature_dial.setSingleStep(5)
        self.temperature_dial.setPageStep(20)
        self.temperature_dial.setSliderPosition(20)
        self.temperature_dial.setTracking(False)
        self.temperature_dial.setInvertedAppearance(False)
        self.temperature_dial.setInvertedControls(False)
        self.temperature_dial.setWrapping(True)
        self.temperature_dial.setNotchesVisible(True)
        self.temperature_dial.setObjectName(_fromUtf8("temperature_dial"))
        self.horizontalLayout.addWidget(self.temperature_dial)
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout = QtGui.QGridLayout(self.frame_3)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.kp_line = QtGui.QLineEdit(self.frame_3)
        self.kp_line.setMaximumSize(QtCore.QSize(50, 16777215))
        self.kp_line.setObjectName(_fromUtf8("kp_line"))
        self.gridLayout.addWidget(self.kp_line, 0, 1, 1, 1)
        self.kd_line = QtGui.QLineEdit(self.frame_3)
        self.kd_line.setMaximumSize(QtCore.QSize(50, 16777215))
        self.kd_line.setObjectName(_fromUtf8("kd_line"))
        self.gridLayout.addWidget(self.kd_line, 3, 1, 1, 1)
        self.ki_line = QtGui.QLineEdit(self.frame_3)
        self.ki_line.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ki_line.setObjectName(_fromUtf8("ki_line"))
        self.gridLayout.addWidget(self.ki_line, 2, 1, 1, 1)
        self.toolButton = QtGui.QToolButton(self.frame_3)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout.addWidget(self.toolButton, 0, 2, 1, 1)
        self.toolButton_2 = QtGui.QToolButton(self.frame_3)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.gridLayout.addWidget(self.toolButton_2, 2, 2, 1, 1)
        self.toolButton_3 = QtGui.QToolButton(self.frame_3)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.gridLayout.addWidget(self.toolButton_3, 3, 2, 1, 1)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.plt_widget = QtGui.QWidget(self.centralWidget)
        self.plt_widget.setAutoFillBackground(True)
        self.plt_widget.setObjectName(_fromUtf8("plt_widget"))
        self.pltvl = QtGui.QVBoxLayout(self.plt_widget)
        self.pltvl.setMargin(11)
        self.pltvl.setSpacing(6)
        self.pltvl.setObjectName(_fromUtf8("pltvl"))
        self.verticalLayout.addWidget(self.plt_widget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 480, 15))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Peltier", None))
        self.label_8.setText(_translate("MainWindow", "TCP", None))
        self.label_12.setText(_translate("MainWindow", "Client", None))
        self.label_9.setText(_translate("MainWindow", "Host Address", None))
        self.label_10.setText(_translate("MainWindow", "Port", None))
        self.pushButton.setText(_translate("MainWindow", "PushButton", None))
        self.label_3.setText(_translate("MainWindow", "Temperature Control", None))
        self.label.setText(_translate("MainWindow", "Desired", None))
        self.desired_line.setText(_translate("MainWindow", "35", None))
        self.startbutton.setText(_translate("MainWindow", "Start/Stop", None))
        self.clear_button.setText(_translate("MainWindow", "Clear", None))
        self.label_2.setText(_translate("MainWindow", "Current", None))
        self.label_6.setText(_translate("MainWindow", "Kd", None))
        self.label_4.setText(_translate("MainWindow", "Kp", None))
        self.label_5.setText(_translate("MainWindow", "Ki", None))
        self.kp_line.setText(_translate("MainWindow", "0.9", None))
        self.kd_line.setText(_translate("MainWindow", "0.05", None))
        self.ki_line.setText(_translate("MainWindow", "0.05", None))
        self.toolButton.setText(_translate("MainWindow", "...", None))
        self.toolButton_2.setText(_translate("MainWindow", "...", None))
        self.toolButton_3.setText(_translate("MainWindow", "...", None))
        self.label_7.setText(_translate("MainWindow", "In time", None))

